Update build-macos.yml

diff --git a/.github/workflows/build-macos.yml b/.github/workflows/build-macos.yml
--- a/.github/workflows/build-macos.yml
+++ b/.github/workflows/build-macos.yml
@@ -58,7 +58,14 @@ jobs:
         run: |
           echo "Looking for macdeployqt..."
           find $(brew --prefix qt) -name macdeployqt
-          
+
+
+       - name: Debug Qt tools
+         run: |
+           echo "PATH=$PATH"
+           which macdeployqt || echo "macdeployqt not found"
+           ls $(brew --prefix qt)/bin/macdeployqt
+    
       - name: Deploy Qt libraries
         run: |
           cd build
